#+TITLE: README
#+AUTHOR: yeongcheon

* 소개

모바일 환경에서 사용하는 당겨서 새로고침(pull to refresh) 라이브러리입니다.

찾다찾다 맘에 드는게 없어서 하나 만들어봤어요. 점차 개선해나가겠습니다.

* 예제
[[./projects/example/src/app][link]]
** app.component.html
   #+BEGIN_SRC html
   <ngx-pull-to-refresh [spinnerColor]="#ff0000" (refresh)="alert('refresh');" (loadMore)="alert('loadmore');">
     <div style="height: 3000px">long content</div>
   </ngx-pull-to-refresh>
   #+END_SRC
** app.component.ts
   #+BEGIN_SRC typescript
import { Component } from '@angular/core';
import { Subject } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'example';

  myRefreshEvent(event: Subject<any>, message: string) {
    setTimeout(() => {
      alert(message);
      event.next();
    }, 3000);
  }

  alert(message: string) {
    alert(message);
  }
}
   #+END_SRC

* License

  The MIT License (MIT)

  Copyright (c) 2019 YeongCheon Kim

  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
